# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x] # slowest first
        os: [macos-latest, windows-latest, ubuntu-latest] # slowest first

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install && npm run build

  docs:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: Build docs on node 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install && npm run build
    - uses: actions/upload-artifact@v2
      with:
        name: docs-dir
        path: docs/docs/
    - uses: actions/upload-artifact@v2
      with:
        name: base-package
        path: package.json
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
    - run: |
        rm -rf docs/current/
    - uses: actions/download-artifact@v2
      with:
        name: docs-dir
        path: docs/docs/current/
    - uses: actions/download-artifact@v2
      with:
        name: base-package
        path: base-package.json
    - run: |
        npm install rimraf
        node archive_docs_by_version.js
        git config user.name "DocBot (github-actions, see node workflow)"
        git config user.email github-actions@github.com
        git add .
        git commit -m "auto-bump docs"
        git push
